"""Cross-runtime commitment vectors generated by the installed bnbagent SDK."""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from bnbagent.erc8183.schema import DeliverableManifest
from web3 import Web3

FIXTURE = Path(__file__).with_name("fixtures") / "deliverable_manifest_vectors.json"
CONTRACTS = {
    "commerce": "0xa206c0517b6371c6638cd9e4a42cc9f02a33b0de",
    "router": "0xd7d36d66d2f1b608a0f943f722d27e3744f66f25",
    "policy": "0x4f4678d4439fec812ac7674bb3efb4c8f5fb78a6",
}


def _vectors() -> list[dict[str, object]]:
    cases = [
        (
            "unicode-and-large-integers",
            2**60 + 7,
            {
                "nested": [{"z": 2, "a": 1}],
                "\ue000": "bmp",
                "\U00010000": "astral",
                "large": 2**200,
            },
        ),
        (
            "python-floats",
            42,
            {
                "small": 1e-7,
                "large": 1e20,
                "negative_zero": -0.0,
                "positive_infinity": float("inf"),
                "not_a_number": float("nan"),
            },
        ),
    ]
    vectors: list[dict[str, object]] = []
    for name, job_id, metadata in cases:
        manifest = DeliverableManifest(
            version=1,
            job_id=job_id,
            chain_id=97,
            contracts=CONTRACTS,
            response={
                "content": f"# SDK vector: {name}",
                "content_type": "text/plain",
            },
            metadata=metadata,
        )
        canonical = json.dumps(
            manifest.to_dict(),
            sort_keys=True,
            separators=(",", ":"),
        )
        vectors.append(
            {
                "name": name,
                "manifest": canonical,
                "commitment": Web3.to_hex(manifest.manifest_hash()),
                "job_id": str(job_id),
                "chain_id": "97",
                "contracts": CONTRACTS,
                "content": f"# SDK vector: {name}",
            }
        )
    return vectors


class DeliverableContractVectorTests(unittest.TestCase):
    def test_committed_vectors_match_the_installed_sdk(self) -> None:
        committed = json.loads(FIXTURE.read_text(encoding="utf-8"))
        self.assertEqual(committed, _vectors())


if __name__ == "__main__":
    unittest.main()
