import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { keccak256, toUtf8Bytes } from "ethers";
import { MAX_PAYLOAD_BYTES } from "./gateway.js";
import { verifyDeliverableManifest } from "./deliverable.js";

const JOB_ID = 2n ** 60n + 7n;
const MAX_JSON_NESTING_DEPTH = 128;
const NESTING_DEPTH_ERROR =
  "DeliverableManifest exceeds the maximum JSON nesting depth";
const CONTRACTS = {
  commerce: "0xa206c0517b6371c6638cd9e4a42cc9f02a33b0de",
  router: "0xd7d36d66d2f1b608a0f943f722d27e3744f66f25",
  policy: "0x4f4678d4439fec812ac7674bb3efb4c8f5fb78a6",
};

interface SdkCommitmentVector {
  name: string;
  manifest: string;
  commitment: string;
  job_id: string;
  chain_id: string;
  contracts: typeof CONTRACTS;
  content: string;
}

const sdkCommitmentVectors = JSON.parse(
  readFileSync(
    new URL(
      "../../stockanalyst/app/agent/tests/fixtures/deliverable_manifest_vectors.json",
      import.meta.url,
    ),
    "utf8",
  ),
) as SdkCommitmentVector[];

function canonicalManifest(content = "# verified"): string {
  return `{"chain_id":97,"contracts":{"commerce":"${CONTRACTS.commerce}","policy":"${CONTRACTS.policy}","router":"${CONTRACTS.router}"},"job_id":${JOB_ID},"metadata":{"job_id":${JOB_ID},"nested":[{"a":1,"b":2}]},"response":{"content":${JSON.stringify(content)},"content_type":"text/plain"},"version":1}`;
}

function manifestWithMetadata(metadataJson: string): string {
  return `{"chain_id":97,"contracts":{"commerce":"${CONTRACTS.commerce}","policy":"${CONTRACTS.policy}","router":"${CONTRACTS.router}"},"job_id":${JOB_ID},"metadata":${metadataJson},"response":{"content":"# verified","content_type":"text/plain"},"version":1}`;
}

function expectation(raw: string) {
  return {
    jobId: JOB_ID,
    chainId: 97n,
    contracts: CONTRACTS,
    commitment: keccak256(toUtf8Bytes(raw)),
  };
}

function nestedObjects(depth: number): string {
  return `${'{"level":'.repeat(depth)}"leaf"${"}".repeat(depth)}`;
}

function nestedArrays(depth: number): string {
  return `${"[".repeat(depth)}"leaf"${"]".repeat(depth)}`;
}

function assertNestingDepthError(callback: () => unknown): void {
  assert.throws(callback, (error: unknown) => {
    assert.ok(error instanceof Error);
    assert.equal(error.message, NESTING_DEPTH_ERROR);
    return true;
  });
}

test("verifies an SDK manifest with a job id above 2^53", () => {
  const raw = canonicalManifest();
  assert.equal(verifyDeliverableManifest(raw, expectation(raw)), "# verified");
});

test("verifies commitments generated by the installed Python SDK", () => {
  for (const vector of sdkCommitmentVectors) {
    assert.equal(
      verifyDeliverableManifest(vector.manifest, {
        jobId: BigInt(vector.job_id),
        chainId: BigInt(vector.chain_id),
        contracts: vector.contracts,
        commitment: vector.commitment,
      }),
      vector.content,
      vector.name,
    );
  }
});

test("canonicalizes key order and whitespace before comparing the commitment", () => {
  const canonical = canonicalManifest();
  const reordered = `{
    "version": 1,
    "response": {"content_type": "text/plain", "content": "# verified"},
    "metadata": {"nested": [{"a": 1, "b": 2}], "job_id": ${JOB_ID}},
    "job_id": ${JOB_ID},
    "contracts": {
      "router": "${CONTRACTS.router}",
      "policy": "${CONTRACTS.policy}",
      "commerce": "${CONTRACTS.commerce}"
    },
    "chain_id": 97
  }`;
  assert.equal(
    verifyDeliverableManifest(reordered, expectation(canonical)),
    "# verified",
  );
});

test("matches SDK key ordering for BMP and astral metadata keys", () => {
  const sdkCanonical = `{"chain_id":97,"contracts":{"commerce":"${CONTRACTS.commerce}","policy":"${CONTRACTS.policy}","router":"${CONTRACTS.router}"},"job_id":${JOB_ID},"metadata":{"\\ue000":"bmp","\\ud800\\udc00":"astral"},"response":{"content":"# verified","content_type":"text/plain"},"version":1}`;
  assert.equal(
    verifyDeliverableManifest(sdkCanonical, expectation(sdkCanonical)),
    "# verified",
  );
});

test("keeps root and nested __proto__ extension keys in the commitment", () => {
  const sdkCanonical = `{"\\u0000__proto__":"sentinel collision","__proto__":{"retained":true},"chain_id":97,"contracts":{"commerce":"${CONTRACTS.commerce}","policy":"${CONTRACTS.policy}","router":"${CONTRACTS.router}"},"job_id":${JOB_ID},"metadata":{"__proto__":{"nested":true}},"response":{"content":"# verified","content_type":"text/plain"},"version":1}`;
  assert.equal(
    verifyDeliverableManifest(sdkCanonical, expectation(sdkCanonical)),
    "# verified",
  );
});

test("rejects a JSON object spoofing the required version number node", () => {
  const canonical = canonicalManifest();
  const spoofed = canonical.replace(
    '"version":1',
    '"version":{"hidden":"uncommitted","isLosslessNumber":true,"value":"1"}',
  );
  assert.throws(
    () => verifyDeliverableManifest(spoofed, expectation(canonical)),
    /version/i,
  );
});

test("does not omit a marker-spoofed extension object from the commitment", () => {
  const canonical = canonicalManifest().replace(
    `"metadata":{"job_id":${JOB_ID},"nested":[{"a":1,"b":2}]}`,
    '"metadata":{"spoofed":7}',
  );
  const spoofed = canonical.replace(
    '"spoofed":7',
    '"spoofed":{"hidden":"uncommitted","isLosslessNumber":true,"value":"7"}',
  );
  assert.throws(
    () => verifyDeliverableManifest(spoofed, expectation(canonical)),
    /commitment does not match/i,
  );
});

test("does not confuse array values, sibling keys, or string contents with duplicates", () => {
  const canonical = manifestWithMetadata(
    '{"array":["same","same"],"left":{"x":1},"right":{"x":2},"text":"{\\"x\\":1,\\"x\\":2}"}',
  );
  assert.equal(
    verifyDeliverableManifest(canonical, expectation(canonical)),
    "# verified",
  );
});

test("rejects duplicate required keys at the manifest root", () => {
  const canonical = canonicalManifest();
  const duplicated = canonical.replace(
    '"version":1',
    '"version":1,"version":1',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects identical duplicate keys in a nested object", () => {
  const canonical = manifestWithMetadata('{"nested":{"same":"value"}}');
  const duplicated = manifestWithMetadata(
    '{"nested":{"same":"value","same":"value"}}',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects duplicate keys inside an object nested in an array", () => {
  const canonical = manifestWithMetadata('{"items":[{"same":"value"}]}');
  const duplicated = manifestWithMetadata(
    '{"items":[{"same":"value","same":"value"}]}',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects duplicate decoded keys with different escape spellings", () => {
  const canonical = manifestWithMetadata('{"nested":{"x":1}}');
  const duplicated = manifestWithMetadata(
    '{"nested":{"x":1,"\\u0078":1}}',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects escaped duplicate __proto__ keys before sentinel protection", () => {
  const canonical = manifestWithMetadata('{"__proto__":{"retained":true}}');
  const duplicated = manifestWithMetadata(
    '{"__proto__":{"retained":true},"\\u005f\\u005fproto\\u005f\\u005f":{"retained":true}}',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects marker-object and number values under a duplicate key", () => {
  const canonical = manifestWithMetadata('{"value":7}');
  const duplicated = manifestWithMetadata(
    '{"value":{"isLosslessNumber":true,"value":"7"},"value":7}',
  );
  assert.throws(
    () => verifyDeliverableManifest(duplicated, expectation(canonical)),
    /JSON|duplicate/i,
  );
});

test("rejects object nesting deeper than 128 containers", () => {
  const overDepth = manifestWithMetadata(
    nestedObjects(MAX_JSON_NESTING_DEPTH),
  );
  assertNestingDepthError(
    () => verifyDeliverableManifest(overDepth, expectation(overDepth)),
  );
});

test("rejects array nesting deeper than 128 containers", () => {
  const overDepth = manifestWithMetadata(
    nestedArrays(MAX_JSON_NESTING_DEPTH),
  );
  assertNestingDepthError(
    () => verifyDeliverableManifest(overDepth, expectation(overDepth)),
  );
});

test("accepts object nesting at exactly 128 containers", () => {
  const atBoundary = manifestWithMetadata(
    nestedObjects(MAX_JSON_NESTING_DEPTH - 1),
  );
  assert.equal(
    verifyDeliverableManifest(atBoundary, expectation(atBoundary)),
    "# verified",
  );
});

test("accepts array nesting at exactly 128 containers", () => {
  const atBoundary = manifestWithMetadata(
    nestedArrays(MAX_JSON_NESTING_DEPTH - 1),
  );
  assert.equal(
    verifyDeliverableManifest(atBoundary, expectation(atBoundary)),
    "# verified",
  );
});

// Fixed outputs from CPython 3.14.5:
// json.dumps(json.loads(token), separators=(",", ":"))
for (const { name, canonicalToken, spellings } of [
  {
    name: "1.0",
    canonicalToken: "1.0",
    spellings: ["1.0", "1e0", "1.00"],
  },
  {
    name: "1e-07",
    canonicalToken: "1e-07",
    spellings: ["1e-07", "0.0000001", "10e-8"],
  },
  {
    name: "1e+20",
    canonicalToken: "1e+20",
    spellings: ["1e+20", "100000000000000000000.0", "10e19"],
  },
  {
    name: "-0.0",
    canonicalToken: "-0.0",
    spellings: ["-0.0", "-0e0", "-0.000"],
  },
] as const) {
  test(`matches the CPython numeric canonical form for ${name} and equivalent spellings`, () => {
    const sdkCanonical = manifestWithMetadata(`{"value":${canonicalToken}}`);
    for (const spelling of spellings) {
      assert.equal(
        verifyDeliverableManifest(
          manifestWithMetadata(`{"value":${spelling}}`),
          expectation(sdkCanonical),
        ),
        "# verified",
      );
    }
  });
}

for (const { name, inputToken, canonicalToken } of [
  { name: "positive overflow", inputToken: "1e400", canonicalToken: "Infinity" },
  { name: "negative overflow", inputToken: "-1e400", canonicalToken: "-Infinity" },
  { name: "positive underflow", inputToken: "1e-4000", canonicalToken: "0.0" },
  { name: "negative underflow", inputToken: "-1e-4000", canonicalToken: "-0.0" },
] as const) {
  test(`matches CPython json.loads/json.dumps ${name} behavior`, () => {
    const sdkCanonical = manifestWithMetadata(`{"value":${canonicalToken}}`);
    assert.equal(
      verifyDeliverableManifest(
        manifestWithMetadata(`{"value":${inputToken}}`),
        expectation(sdkCanonical),
      ),
      "# verified",
    );
  });
}

test("preserves CPython's maximum exact integer and rejects the next digit", () => {
  const maximumInteger = "1".repeat(4_300);
  const sdkCanonical = manifestWithMetadata(`{"value":${maximumInteger}}`);
  assert.equal(
    verifyDeliverableManifest(sdkCanonical, expectation(sdkCanonical)),
    "# verified",
  );

  const oversizedInteger = `1${maximumInteger}`;
  assert.throws(
    () => verifyDeliverableManifest(
      manifestWithMetadata(`{"value":${oversizedInteger}}`),
      expectation(manifestWithMetadata(`{"value":${oversizedInteger}}`)),
    ),
    /integer.*4,?300|4,?300.*integer/i,
  );
});

test("rejects a changed response even when the manifest context is valid", () => {
  const canonical = canonicalManifest();
  const changed = canonical.replace("# verified", "# replaced");
  assert.throws(
    () => verifyDeliverableManifest(changed, expectation(canonical)),
    /commitment does not match/i,
  );
});

for (const [name, mutate, error] of [
  ["job", (raw: string) => raw.replace(JOB_ID.toString(), (JOB_ID + 1n).toString()), /job_id/i],
  ["chain", (raw: string) => raw.replace('"chain_id":97', '"chain_id":56'), /chain_id/i],
  ["commerce", (raw: string) => raw.replace(CONTRACTS.commerce, "0x0000000000000000000000000000000000000001"), /commerce/i],
  ["router", (raw: string) => raw.replace(CONTRACTS.router, "0x0000000000000000000000000000000000000002"), /router/i],
  ["policy", (raw: string) => raw.replace(CONTRACTS.policy, "0x0000000000000000000000000000000000000003"), /policy/i],
] as const) {
  test(`rejects a manifest for the wrong ${name}`, () => {
    const canonical = canonicalManifest();
    assert.throws(
      () => verifyDeliverableManifest(mutate(canonical), expectation(canonical)),
      error,
    );
  });
}

test("rejects malformed, unsupported, incomplete, and oversized manifests", () => {
  const canonical = canonicalManifest();
  const expected = expectation(canonical);
  assert.throws(() => verifyDeliverableManifest("{", expected), /JSON/i);
  assert.throws(
    () => verifyDeliverableManifest(canonical.replace('"version":1', '"version":2'), expected),
    /version/i,
  );
  assert.throws(
    () => verifyDeliverableManifest(canonical.replace('"content_type":"text/plain"', '"content_type":7'), expected),
    /content_type/i,
  );
  assert.throws(
    () => verifyDeliverableManifest(`{"padding":"${"x".repeat(MAX_PAYLOAD_BYTES)}"}`, expected),
    /size/i,
  );
});
